using System;

namespace Curryfy
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a tool. 
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public static partial class CurryfyExtensions
    { 
        // 1
        public static Action<T2, T3> ApplyPartial<T1, T2, T3>(this Action<T1, T2, T3> function, T1 arg1)
            => (arg2, arg3) => function(arg1, arg2, arg3);
        
        // 2
        public static Action<T1, T3> ApplyPartial<T1, T2, T3>(this Action<T1, T2, T3> function, T2 arg2)
            => (arg1, arg3) => function(arg1, arg2, arg3);
        
        // 3
        public static Action<T3> ApplyPartial<T1, T2, T3>(this Action<T1, T2, T3> function, T1 arg1, T2 arg2)
            => (arg3) => function(arg1, arg2, arg3);
        
        // 4
        public static Action<T1, T2> ApplyPartial<T1, T2, T3>(this Action<T1, T2, T3> function, T3 arg3)
            => (arg1, arg2) => function(arg1, arg2, arg3);
        
        // 5
        public static Action<T2> ApplyPartial<T1, T2, T3>(this Action<T1, T2, T3> function, T1 arg1, T3 arg3)
            => (arg2) => function(arg1, arg2, arg3);
        
        // 6
        public static Action<T1> ApplyPartial<T1, T2, T3>(this Action<T1, T2, T3> function, T2 arg2, T3 arg3)
            => (arg1) => function(arg1, arg2, arg3);
    }
}
