using System;

namespace Curryfy
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a tool. 
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public static partial class CurryfyExtensions
    { 
        // 1
        public static Action<T2, T3, T4, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1)
            => (arg2, arg3, arg4, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 2
        public static Action<T1, T3, T4, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2)
            => (arg1, arg3, arg4, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 3
        public static Action<T3, T4, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2)
            => (arg3, arg4, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 4
        public static Action<T1, T2, T4, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3)
            => (arg1, arg2, arg4, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 5
        public static Action<T2, T4, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3)
            => (arg2, arg4, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 6
        public static Action<T1, T4, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3)
            => (arg1, arg4, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 7
        public static Action<T4, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3)
            => (arg4, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 8
        public static Action<T1, T2, T3, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4)
            => (arg1, arg2, arg3, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 9
        public static Action<T2, T3, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4)
            => (arg2, arg3, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 10
        public static Action<T1, T3, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4)
            => (arg1, arg3, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 11
        public static Action<T3, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4)
            => (arg3, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 12
        public static Action<T1, T2, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4)
            => (arg1, arg2, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 13
        public static Action<T2, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4)
            => (arg2, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 14
        public static Action<T1, T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4)
            => (arg1, arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 15
        public static Action<T5, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
            => (arg5, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 16
        public static Action<T1, T2, T3, T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5)
            => (arg1, arg2, arg3, arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 17
        public static Action<T2, T3, T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5)
            => (arg2, arg3, arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 18
        public static Action<T1, T3, T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5)
            => (arg1, arg3, arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 19
        public static Action<T3, T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5)
            => (arg3, arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 20
        public static Action<T1, T2, T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5)
            => (arg1, arg2, arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 21
        public static Action<T2, T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5)
            => (arg2, arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 22
        public static Action<T1, T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5)
            => (arg1, arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 23
        public static Action<T4, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5)
            => (arg4, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 24
        public static Action<T1, T2, T3, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5)
            => (arg1, arg2, arg3, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 25
        public static Action<T2, T3, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5)
            => (arg2, arg3, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 26
        public static Action<T1, T3, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5)
            => (arg1, arg3, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 27
        public static Action<T3, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5)
            => (arg3, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 28
        public static Action<T1, T2, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5)
            => (arg1, arg2, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 29
        public static Action<T2, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5)
            => (arg2, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 30
        public static Action<T1, T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
            => (arg1, arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 31
        public static Action<T6, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
            => (arg6, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 32
        public static Action<T1, T2, T3, T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T6 arg6)
            => (arg1, arg2, arg3, arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 33
        public static Action<T2, T3, T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T6 arg6)
            => (arg2, arg3, arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 34
        public static Action<T1, T3, T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T6 arg6)
            => (arg1, arg3, arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 35
        public static Action<T3, T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T6 arg6)
            => (arg3, arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 36
        public static Action<T1, T2, T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T6 arg6)
            => (arg1, arg2, arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 37
        public static Action<T2, T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T6 arg6)
            => (arg2, arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 38
        public static Action<T1, T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T6 arg6)
            => (arg1, arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 39
        public static Action<T4, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T6 arg6)
            => (arg4, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 40
        public static Action<T1, T2, T3, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T6 arg6)
            => (arg1, arg2, arg3, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 41
        public static Action<T2, T3, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T6 arg6)
            => (arg2, arg3, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 42
        public static Action<T1, T3, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T6 arg6)
            => (arg1, arg3, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 43
        public static Action<T3, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T6 arg6)
            => (arg3, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 44
        public static Action<T1, T2, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T6 arg6)
            => (arg1, arg2, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 45
        public static Action<T2, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T6 arg6)
            => (arg2, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 46
        public static Action<T1, T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T6 arg6)
            => (arg1, arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 47
        public static Action<T5, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T6 arg6)
            => (arg5, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 48
        public static Action<T1, T2, T3, T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5, T6 arg6)
            => (arg1, arg2, arg3, arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 49
        public static Action<T2, T3, T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5, T6 arg6)
            => (arg2, arg3, arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 50
        public static Action<T1, T3, T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5, T6 arg6)
            => (arg1, arg3, arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 51
        public static Action<T3, T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5, T6 arg6)
            => (arg3, arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 52
        public static Action<T1, T2, T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5, T6 arg6)
            => (arg1, arg2, arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 53
        public static Action<T2, T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5, T6 arg6)
            => (arg2, arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 54
        public static Action<T1, T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5, T6 arg6)
            => (arg1, arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 55
        public static Action<T4, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5, T6 arg6)
            => (arg4, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 56
        public static Action<T1, T2, T3, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5, T6 arg6)
            => (arg1, arg2, arg3, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 57
        public static Action<T2, T3, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5, T6 arg6)
            => (arg2, arg3, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 58
        public static Action<T1, T3, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5, T6 arg6)
            => (arg1, arg3, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 59
        public static Action<T3, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5, T6 arg6)
            => (arg3, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 60
        public static Action<T1, T2, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (arg1, arg2, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 61
        public static Action<T2, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (arg2, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 62
        public static Action<T1, T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (arg1, arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 63
        public static Action<T7, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (arg7, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 64
        public static Action<T1, T2, T3, T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T7 arg7)
            => (arg1, arg2, arg3, arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 65
        public static Action<T2, T3, T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T7 arg7)
            => (arg2, arg3, arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 66
        public static Action<T1, T3, T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T7 arg7)
            => (arg1, arg3, arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 67
        public static Action<T3, T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T7 arg7)
            => (arg3, arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 68
        public static Action<T1, T2, T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T7 arg7)
            => (arg1, arg2, arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 69
        public static Action<T2, T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T7 arg7)
            => (arg2, arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 70
        public static Action<T1, T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T7 arg7)
            => (arg1, arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 71
        public static Action<T4, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T7 arg7)
            => (arg4, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 72
        public static Action<T1, T2, T3, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T7 arg7)
            => (arg1, arg2, arg3, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 73
        public static Action<T2, T3, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T7 arg7)
            => (arg2, arg3, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 74
        public static Action<T1, T3, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T7 arg7)
            => (arg1, arg3, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 75
        public static Action<T3, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T7 arg7)
            => (arg3, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 76
        public static Action<T1, T2, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T7 arg7)
            => (arg1, arg2, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 77
        public static Action<T2, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T7 arg7)
            => (arg2, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 78
        public static Action<T1, T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T7 arg7)
            => (arg1, arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 79
        public static Action<T5, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T7 arg7)
            => (arg5, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 80
        public static Action<T1, T2, T3, T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5, T7 arg7)
            => (arg1, arg2, arg3, arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 81
        public static Action<T2, T3, T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5, T7 arg7)
            => (arg2, arg3, arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 82
        public static Action<T1, T3, T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5, T7 arg7)
            => (arg1, arg3, arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 83
        public static Action<T3, T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5, T7 arg7)
            => (arg3, arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 84
        public static Action<T1, T2, T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5, T7 arg7)
            => (arg1, arg2, arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 85
        public static Action<T2, T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5, T7 arg7)
            => (arg2, arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 86
        public static Action<T1, T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5, T7 arg7)
            => (arg1, arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 87
        public static Action<T4, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5, T7 arg7)
            => (arg4, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 88
        public static Action<T1, T2, T3, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5, T7 arg7)
            => (arg1, arg2, arg3, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 89
        public static Action<T2, T3, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5, T7 arg7)
            => (arg2, arg3, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 90
        public static Action<T1, T3, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5, T7 arg7)
            => (arg1, arg3, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 91
        public static Action<T3, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5, T7 arg7)
            => (arg3, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 92
        public static Action<T1, T2, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5, T7 arg7)
            => (arg1, arg2, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 93
        public static Action<T2, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5, T7 arg7)
            => (arg2, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 94
        public static Action<T1, T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T7 arg7)
            => (arg1, arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 95
        public static Action<T6, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T7 arg7)
            => (arg6, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 96
        public static Action<T1, T2, T3, T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T6 arg6, T7 arg7)
            => (arg1, arg2, arg3, arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 97
        public static Action<T2, T3, T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T6 arg6, T7 arg7)
            => (arg2, arg3, arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 98
        public static Action<T1, T3, T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T6 arg6, T7 arg7)
            => (arg1, arg3, arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 99
        public static Action<T3, T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T6 arg6, T7 arg7)
            => (arg3, arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 100
        public static Action<T1, T2, T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T6 arg6, T7 arg7)
            => (arg1, arg2, arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 101
        public static Action<T2, T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T6 arg6, T7 arg7)
            => (arg2, arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 102
        public static Action<T1, T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T6 arg6, T7 arg7)
            => (arg1, arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 103
        public static Action<T4, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T6 arg6, T7 arg7)
            => (arg4, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 104
        public static Action<T1, T2, T3, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T6 arg6, T7 arg7)
            => (arg1, arg2, arg3, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 105
        public static Action<T2, T3, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T6 arg6, T7 arg7)
            => (arg2, arg3, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 106
        public static Action<T1, T3, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T6 arg6, T7 arg7)
            => (arg1, arg3, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 107
        public static Action<T3, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T6 arg6, T7 arg7)
            => (arg3, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 108
        public static Action<T1, T2, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T6 arg6, T7 arg7)
            => (arg1, arg2, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 109
        public static Action<T2, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T6 arg6, T7 arg7)
            => (arg2, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 110
        public static Action<T1, T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T6 arg6, T7 arg7)
            => (arg1, arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 111
        public static Action<T5, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T6 arg6, T7 arg7)
            => (arg5, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 112
        public static Action<T1, T2, T3, T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg2, arg3, arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 113
        public static Action<T2, T3, T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5, T6 arg6, T7 arg7)
            => (arg2, arg3, arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 114
        public static Action<T1, T3, T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg3, arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 115
        public static Action<T3, T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5, T6 arg6, T7 arg7)
            => (arg3, arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 116
        public static Action<T1, T2, T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg2, arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 117
        public static Action<T2, T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5, T6 arg6, T7 arg7)
            => (arg2, arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 118
        public static Action<T1, T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 119
        public static Action<T4, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5, T6 arg6, T7 arg7)
            => (arg4, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 120
        public static Action<T1, T2, T3, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg2, arg3, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 121
        public static Action<T2, T3, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg2, arg3, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 122
        public static Action<T1, T3, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg3, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 123
        public static Action<T3, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg3, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 124
        public static Action<T1, T2, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg2, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 125
        public static Action<T2, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg2, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 126
        public static Action<T1, T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg1, arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 127
        public static Action<T8> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
            => (arg8) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 128
        public static Action<T1, T2, T3, T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T8 arg8)
            => (arg1, arg2, arg3, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 129
        public static Action<T2, T3, T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T8 arg8)
            => (arg2, arg3, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 130
        public static Action<T1, T3, T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T8 arg8)
            => (arg1, arg3, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 131
        public static Action<T3, T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T8 arg8)
            => (arg3, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 132
        public static Action<T1, T2, T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T8 arg8)
            => (arg1, arg2, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 133
        public static Action<T2, T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T8 arg8)
            => (arg2, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 134
        public static Action<T1, T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T8 arg8)
            => (arg1, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 135
        public static Action<T4, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T8 arg8)
            => (arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 136
        public static Action<T1, T2, T3, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T8 arg8)
            => (arg1, arg2, arg3, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 137
        public static Action<T2, T3, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T8 arg8)
            => (arg2, arg3, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 138
        public static Action<T1, T3, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T8 arg8)
            => (arg1, arg3, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 139
        public static Action<T3, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T8 arg8)
            => (arg3, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 140
        public static Action<T1, T2, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T8 arg8)
            => (arg1, arg2, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 141
        public static Action<T2, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T8 arg8)
            => (arg2, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 142
        public static Action<T1, T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T8 arg8)
            => (arg1, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 143
        public static Action<T5, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T8 arg8)
            => (arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 144
        public static Action<T1, T2, T3, T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5, T8 arg8)
            => (arg1, arg2, arg3, arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 145
        public static Action<T2, T3, T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5, T8 arg8)
            => (arg2, arg3, arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 146
        public static Action<T1, T3, T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5, T8 arg8)
            => (arg1, arg3, arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 147
        public static Action<T3, T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5, T8 arg8)
            => (arg3, arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 148
        public static Action<T1, T2, T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5, T8 arg8)
            => (arg1, arg2, arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 149
        public static Action<T2, T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5, T8 arg8)
            => (arg2, arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 150
        public static Action<T1, T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5, T8 arg8)
            => (arg1, arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 151
        public static Action<T4, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5, T8 arg8)
            => (arg4, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 152
        public static Action<T1, T2, T3, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5, T8 arg8)
            => (arg1, arg2, arg3, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 153
        public static Action<T2, T3, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5, T8 arg8)
            => (arg2, arg3, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 154
        public static Action<T1, T3, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5, T8 arg8)
            => (arg1, arg3, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 155
        public static Action<T3, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5, T8 arg8)
            => (arg3, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 156
        public static Action<T1, T2, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5, T8 arg8)
            => (arg1, arg2, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 157
        public static Action<T2, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5, T8 arg8)
            => (arg2, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 158
        public static Action<T1, T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T8 arg8)
            => (arg1, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 159
        public static Action<T6, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T8 arg8)
            => (arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 160
        public static Action<T1, T2, T3, T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T6 arg6, T8 arg8)
            => (arg1, arg2, arg3, arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 161
        public static Action<T2, T3, T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T6 arg6, T8 arg8)
            => (arg2, arg3, arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 162
        public static Action<T1, T3, T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T6 arg6, T8 arg8)
            => (arg1, arg3, arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 163
        public static Action<T3, T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T6 arg6, T8 arg8)
            => (arg3, arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 164
        public static Action<T1, T2, T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T6 arg6, T8 arg8)
            => (arg1, arg2, arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 165
        public static Action<T2, T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T6 arg6, T8 arg8)
            => (arg2, arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 166
        public static Action<T1, T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T6 arg6, T8 arg8)
            => (arg1, arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 167
        public static Action<T4, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T6 arg6, T8 arg8)
            => (arg4, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 168
        public static Action<T1, T2, T3, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T6 arg6, T8 arg8)
            => (arg1, arg2, arg3, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 169
        public static Action<T2, T3, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T6 arg6, T8 arg8)
            => (arg2, arg3, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 170
        public static Action<T1, T3, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T6 arg6, T8 arg8)
            => (arg1, arg3, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 171
        public static Action<T3, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T6 arg6, T8 arg8)
            => (arg3, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 172
        public static Action<T1, T2, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T6 arg6, T8 arg8)
            => (arg1, arg2, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 173
        public static Action<T2, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T6 arg6, T8 arg8)
            => (arg2, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 174
        public static Action<T1, T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T6 arg6, T8 arg8)
            => (arg1, arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 175
        public static Action<T5, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T6 arg6, T8 arg8)
            => (arg5, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 176
        public static Action<T1, T2, T3, T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg2, arg3, arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 177
        public static Action<T2, T3, T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5, T6 arg6, T8 arg8)
            => (arg2, arg3, arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 178
        public static Action<T1, T3, T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg3, arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 179
        public static Action<T3, T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5, T6 arg6, T8 arg8)
            => (arg3, arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 180
        public static Action<T1, T2, T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg2, arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 181
        public static Action<T2, T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5, T6 arg6, T8 arg8)
            => (arg2, arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 182
        public static Action<T1, T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 183
        public static Action<T4, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5, T6 arg6, T8 arg8)
            => (arg4, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 184
        public static Action<T1, T2, T3, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg2, arg3, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 185
        public static Action<T2, T3, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg2, arg3, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 186
        public static Action<T1, T3, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg3, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 187
        public static Action<T3, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg3, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 188
        public static Action<T1, T2, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg2, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 189
        public static Action<T2, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg2, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 190
        public static Action<T1, T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg1, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 191
        public static Action<T7> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T8 arg8)
            => (arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 192
        public static Action<T1, T2, T3, T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3, arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 193
        public static Action<T2, T3, T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T7 arg7, T8 arg8)
            => (arg2, arg3, arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 194
        public static Action<T1, T3, T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T7 arg7, T8 arg8)
            => (arg1, arg3, arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 195
        public static Action<T3, T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T7 arg7, T8 arg8)
            => (arg3, arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 196
        public static Action<T1, T2, T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T7 arg7, T8 arg8)
            => (arg1, arg2, arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 197
        public static Action<T2, T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T7 arg7, T8 arg8)
            => (arg2, arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 198
        public static Action<T1, T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T7 arg7, T8 arg8)
            => (arg1, arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 199
        public static Action<T4, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T7 arg7, T8 arg8)
            => (arg4, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 200
        public static Action<T1, T2, T3, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 201
        public static Action<T2, T3, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T7 arg7, T8 arg8)
            => (arg2, arg3, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 202
        public static Action<T1, T3, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T7 arg7, T8 arg8)
            => (arg1, arg3, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 203
        public static Action<T3, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T7 arg7, T8 arg8)
            => (arg3, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 204
        public static Action<T1, T2, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T7 arg7, T8 arg8)
            => (arg1, arg2, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 205
        public static Action<T2, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T7 arg7, T8 arg8)
            => (arg2, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 206
        public static Action<T1, T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T7 arg7, T8 arg8)
            => (arg1, arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 207
        public static Action<T5, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T7 arg7, T8 arg8)
            => (arg5, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 208
        public static Action<T1, T2, T3, T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3, arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 209
        public static Action<T2, T3, T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5, T7 arg7, T8 arg8)
            => (arg2, arg3, arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 210
        public static Action<T1, T3, T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg3, arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 211
        public static Action<T3, T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5, T7 arg7, T8 arg8)
            => (arg3, arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 212
        public static Action<T1, T2, T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg2, arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 213
        public static Action<T2, T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5, T7 arg7, T8 arg8)
            => (arg2, arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 214
        public static Action<T1, T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 215
        public static Action<T4, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5, T7 arg7, T8 arg8)
            => (arg4, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 216
        public static Action<T1, T2, T3, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 217
        public static Action<T2, T3, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg2, arg3, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 218
        public static Action<T1, T3, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg3, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 219
        public static Action<T3, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg3, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 220
        public static Action<T1, T2, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg2, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 221
        public static Action<T2, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg2, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 222
        public static Action<T1, T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg1, arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 223
        public static Action<T6> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T7 arg7, T8 arg8)
            => (arg6) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 224
        public static Action<T1, T2, T3, T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3, arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 225
        public static Action<T2, T3, T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T6 arg6, T7 arg7, T8 arg8)
            => (arg2, arg3, arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 226
        public static Action<T1, T3, T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg3, arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 227
        public static Action<T3, T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T6 arg6, T7 arg7, T8 arg8)
            => (arg3, arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 228
        public static Action<T1, T2, T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2, arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 229
        public static Action<T2, T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T6 arg6, T7 arg7, T8 arg8)
            => (arg2, arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 230
        public static Action<T1, T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 231
        public static Action<T4, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T6 arg6, T7 arg7, T8 arg8)
            => (arg4, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 232
        public static Action<T1, T2, T3, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 233
        public static Action<T2, T3, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg2, arg3, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 234
        public static Action<T1, T3, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg3, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 235
        public static Action<T3, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg3, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 236
        public static Action<T1, T2, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 237
        public static Action<T2, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg2, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 238
        public static Action<T1, T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 239
        public static Action<T5> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T6 arg6, T7 arg7, T8 arg8)
            => (arg5) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 240
        public static Action<T1, T2, T3, T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3, arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 241
        public static Action<T2, T3, T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg2, arg3, arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 242
        public static Action<T1, T3, T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg3, arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 243
        public static Action<T3, T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg3, arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 244
        public static Action<T1, T2, T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2, arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 245
        public static Action<T2, T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg2, arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 246
        public static Action<T1, T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 247
        public static Action<T4> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T3 arg3, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg4) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 248
        public static Action<T1, T2, T3> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2, arg3) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 249
        public static Action<T2, T3> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg2, arg3) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 250
        public static Action<T1, T3> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg3) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 251
        public static Action<T3> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T2 arg2, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg3) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 252
        public static Action<T1, T2> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1, arg2) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 253
        public static Action<T2> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T1 arg1, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg2) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
        
        // 254
        public static Action<T1> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T1, T2, T3, T4, T5, T6, T7, T8> function, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
            => (arg1) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
}
