using System;

namespace Curryfy
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a tool. 
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public static partial class PartialDiscardFuncExtensions
    { 
        // 1
        public static Func<T2, T3, T4, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, __ arg4, __ arg5, __ arg6)
            => (_arg2, _arg3, _arg4, _arg5, _arg6) => function(arg1, _arg2, _arg3, _arg4, _arg5, _arg6);
        
        // 2
        public static Func<T1, T3, T4, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, __ arg4, __ arg5, __ arg6)
            => (_arg1, _arg3, _arg4, _arg5, _arg6) => function(_arg1, arg2, _arg3, _arg4, _arg5, _arg6);
        
        // 3
        public static Func<T3, T4, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, __ arg4, __ arg5, __ arg6)
            => (_arg3, _arg4, _arg5, _arg6) => function(arg1, arg2, _arg3, _arg4, _arg5, _arg6);
        
        // 4
        public static Func<T1, T2, T4, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, __ arg4, __ arg5, __ arg6)
            => (_arg1, _arg2, _arg4, _arg5, _arg6) => function(_arg1, _arg2, arg3, _arg4, _arg5, _arg6);
        
        // 5
        public static Func<T2, T4, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, __ arg4, __ arg5, __ arg6)
            => (_arg2, _arg4, _arg5, _arg6) => function(arg1, _arg2, arg3, _arg4, _arg5, _arg6);
        
        // 6
        public static Func<T1, T4, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, __ arg4, __ arg5, __ arg6)
            => (_arg1, _arg4, _arg5, _arg6) => function(_arg1, arg2, arg3, _arg4, _arg5, _arg6);
        
        // 7
        public static Func<T4, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, T3 arg3, __ arg4, __ arg5, __ arg6)
            => (_arg4, _arg5, _arg6) => function(arg1, arg2, arg3, _arg4, _arg5, _arg6);
        
        // 8
        public static Func<T1, T2, T3, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, __ arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg1, _arg2, _arg3, _arg5, _arg6) => function(_arg1, _arg2, _arg3, arg4, _arg5, _arg6);
        
        // 9
        public static Func<T2, T3, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg2, _arg3, _arg5, _arg6) => function(arg1, _arg2, _arg3, arg4, _arg5, _arg6);
        
        // 10
        public static Func<T1, T3, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg1, _arg3, _arg5, _arg6) => function(_arg1, arg2, _arg3, arg4, _arg5, _arg6);
        
        // 11
        public static Func<T3, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg3, _arg5, _arg6) => function(arg1, arg2, _arg3, arg4, _arg5, _arg6);
        
        // 12
        public static Func<T1, T2, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg1, _arg2, _arg5, _arg6) => function(_arg1, _arg2, arg3, arg4, _arg5, _arg6);
        
        // 13
        public static Func<T2, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg2, _arg5, _arg6) => function(arg1, _arg2, arg3, arg4, _arg5, _arg6);
        
        // 14
        public static Func<T1, T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg1, _arg5, _arg6) => function(_arg1, arg2, arg3, arg4, _arg5, _arg6);
        
        // 15
        public static Func<T5, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, __ arg5, __ arg6)
            => (_arg5, _arg6) => function(arg1, arg2, arg3, arg4, _arg5, _arg6);
        
        // 16
        public static Func<T1, T2, T3, T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, __ arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg1, _arg2, _arg3, _arg4, _arg6) => function(_arg1, _arg2, _arg3, _arg4, arg5, _arg6);
        
        // 17
        public static Func<T2, T3, T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg2, _arg3, _arg4, _arg6) => function(arg1, _arg2, _arg3, _arg4, arg5, _arg6);
        
        // 18
        public static Func<T1, T3, T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg1, _arg3, _arg4, _arg6) => function(_arg1, arg2, _arg3, _arg4, arg5, _arg6);
        
        // 19
        public static Func<T3, T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg3, _arg4, _arg6) => function(arg1, arg2, _arg3, _arg4, arg5, _arg6);
        
        // 20
        public static Func<T1, T2, T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg1, _arg2, _arg4, _arg6) => function(_arg1, _arg2, arg3, _arg4, arg5, _arg6);
        
        // 21
        public static Func<T2, T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg2, _arg4, _arg6) => function(arg1, _arg2, arg3, _arg4, arg5, _arg6);
        
        // 22
        public static Func<T1, T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg1, _arg4, _arg6) => function(_arg1, arg2, arg3, _arg4, arg5, _arg6);
        
        // 23
        public static Func<T4, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, T3 arg3, __ arg4, T5 arg5, __ arg6)
            => (_arg4, _arg6) => function(arg1, arg2, arg3, _arg4, arg5, _arg6);
        
        // 24
        public static Func<T1, T2, T3, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, __ arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg1, _arg2, _arg3, _arg6) => function(_arg1, _arg2, _arg3, arg4, arg5, _arg6);
        
        // 25
        public static Func<T2, T3, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg2, _arg3, _arg6) => function(arg1, _arg2, _arg3, arg4, arg5, _arg6);
        
        // 26
        public static Func<T1, T3, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg1, _arg3, _arg6) => function(_arg1, arg2, _arg3, arg4, arg5, _arg6);
        
        // 27
        public static Func<T3, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg3, _arg6) => function(arg1, arg2, _arg3, arg4, arg5, _arg6);
        
        // 28
        public static Func<T1, T2, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg1, _arg2, _arg6) => function(_arg1, _arg2, arg3, arg4, arg5, _arg6);
        
        // 29
        public static Func<T2, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg2, _arg6) => function(arg1, _arg2, arg3, arg4, arg5, _arg6);
        
        // 30
        public static Func<T1, T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg1, _arg6) => function(_arg1, arg2, arg3, arg4, arg5, _arg6);
        
        // 31
        public static Func<T6, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, __ arg6)
            => (_arg6) => function(arg1, arg2, arg3, arg4, arg5, _arg6);
        
        // 32
        public static Func<T1, T2, T3, T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, __ arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg1, _arg2, _arg3, _arg4, _arg5) => function(_arg1, _arg2, _arg3, _arg4, _arg5, arg6);
        
        // 33
        public static Func<T2, T3, T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg2, _arg3, _arg4, _arg5) => function(arg1, _arg2, _arg3, _arg4, _arg5, arg6);
        
        // 34
        public static Func<T1, T3, T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg1, _arg3, _arg4, _arg5) => function(_arg1, arg2, _arg3, _arg4, _arg5, arg6);
        
        // 35
        public static Func<T3, T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg3, _arg4, _arg5) => function(arg1, arg2, _arg3, _arg4, _arg5, arg6);
        
        // 36
        public static Func<T1, T2, T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg1, _arg2, _arg4, _arg5) => function(_arg1, _arg2, arg3, _arg4, _arg5, arg6);
        
        // 37
        public static Func<T2, T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg2, _arg4, _arg5) => function(arg1, _arg2, arg3, _arg4, _arg5, arg6);
        
        // 38
        public static Func<T1, T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg1, _arg4, _arg5) => function(_arg1, arg2, arg3, _arg4, _arg5, arg6);
        
        // 39
        public static Func<T4, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, T3 arg3, __ arg4, __ arg5, T6 arg6)
            => (_arg4, _arg5) => function(arg1, arg2, arg3, _arg4, _arg5, arg6);
        
        // 40
        public static Func<T1, T2, T3, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, __ arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg1, _arg2, _arg3, _arg5) => function(_arg1, _arg2, _arg3, arg4, _arg5, arg6);
        
        // 41
        public static Func<T2, T3, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg2, _arg3, _arg5) => function(arg1, _arg2, _arg3, arg4, _arg5, arg6);
        
        // 42
        public static Func<T1, T3, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg1, _arg3, _arg5) => function(_arg1, arg2, _arg3, arg4, _arg5, arg6);
        
        // 43
        public static Func<T3, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg3, _arg5) => function(arg1, arg2, _arg3, arg4, _arg5, arg6);
        
        // 44
        public static Func<T1, T2, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg1, _arg2, _arg5) => function(_arg1, _arg2, arg3, arg4, _arg5, arg6);
        
        // 45
        public static Func<T2, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg2, _arg5) => function(arg1, _arg2, arg3, arg4, _arg5, arg6);
        
        // 46
        public static Func<T1, T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg1, _arg5) => function(_arg1, arg2, arg3, arg4, _arg5, arg6);
        
        // 47
        public static Func<T5, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, __ arg5, T6 arg6)
            => (_arg5) => function(arg1, arg2, arg3, arg4, _arg5, arg6);
        
        // 48
        public static Func<T1, T2, T3, T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, __ arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg1, _arg2, _arg3, _arg4) => function(_arg1, _arg2, _arg3, _arg4, arg5, arg6);
        
        // 49
        public static Func<T2, T3, T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg2, _arg3, _arg4) => function(arg1, _arg2, _arg3, _arg4, arg5, arg6);
        
        // 50
        public static Func<T1, T3, T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg1, _arg3, _arg4) => function(_arg1, arg2, _arg3, _arg4, arg5, arg6);
        
        // 51
        public static Func<T3, T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg3, _arg4) => function(arg1, arg2, _arg3, _arg4, arg5, arg6);
        
        // 52
        public static Func<T1, T2, T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg1, _arg2, _arg4) => function(_arg1, _arg2, arg3, _arg4, arg5, arg6);
        
        // 53
        public static Func<T2, T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg2, _arg4) => function(arg1, _arg2, arg3, _arg4, arg5, arg6);
        
        // 54
        public static Func<T1, T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg1, _arg4) => function(_arg1, arg2, arg3, _arg4, arg5, arg6);
        
        // 55
        public static Func<T4, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, T3 arg3, __ arg4, T5 arg5, T6 arg6)
            => (_arg4) => function(arg1, arg2, arg3, _arg4, arg5, arg6);
        
        // 56
        public static Func<T1, T2, T3, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, __ arg3, T4 arg4, T5 arg5, T6 arg6)
            => (_arg1, _arg2, _arg3) => function(_arg1, _arg2, _arg3, arg4, arg5, arg6);
        
        // 57
        public static Func<T2, T3, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, __ arg3, T4 arg4, T5 arg5, T6 arg6)
            => (_arg2, _arg3) => function(arg1, _arg2, _arg3, arg4, arg5, arg6);
        
        // 58
        public static Func<T1, T3, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, __ arg3, T4 arg4, T5 arg5, T6 arg6)
            => (_arg1, _arg3) => function(_arg1, arg2, _arg3, arg4, arg5, arg6);
        
        // 59
        public static Func<T3, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, T2 arg2, __ arg3, T4 arg4, T5 arg5, T6 arg6)
            => (_arg3) => function(arg1, arg2, _arg3, arg4, arg5, arg6);
        
        // 60
        public static Func<T1, T2, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, __ arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (_arg1, _arg2) => function(_arg1, _arg2, arg3, arg4, arg5, arg6);
        
        // 61
        public static Func<T2, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, T1 arg1, __ arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (_arg2) => function(arg1, _arg2, arg3, arg4, arg5, arg6);
        
        // 62
        public static Func<T1, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, TResult>(this Func<T1, T2, T3, T4, T5, T6, TResult> function, __ arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (_arg1) => function(_arg1, arg2, arg3, arg4, arg5, arg6);
    }
}
