using System;

namespace Curryfy
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a tool. 
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public static partial class PartialDiscardFuncExtensions
    { 
        // 1
        public static Func<T2, TResult> ApplyPartial<T1, T2, TResult>(this Func<T1, T2, TResult> function, T1 arg1, __ arg2)
            => (_arg2) => function(arg1, _arg2);
        
        // 2
        public static Func<T1, TResult> ApplyPartial<T1, T2, TResult>(this Func<T1, T2, TResult> function, __ arg1, T2 arg2)
            => (_arg1) => function(_arg1, arg2);
    }
}
