using System;

namespace Curryfy
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a tool. 
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public static partial class PartialSubsetActionExtensions
    { 
        // 1
        public static Action<T2, T3, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1)
            => (arg2, arg3, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 2
        public static Action<T1, T3, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T2 arg2)
            => (arg1, arg3, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 3
        public static Action<T3, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T2 arg2)
            => (arg3, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 4
        public static Action<T1, T2, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T3 arg3)
            => (arg1, arg2, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 5
        public static Action<T2, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T3 arg3)
            => (arg2, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 6
        public static Action<T1, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T2 arg2, T3 arg3)
            => (arg1, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 7
        public static Action<T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T2 arg2, T3 arg3)
            => (arg4) => function(arg1, arg2, arg3, arg4);
        
        // 8
        public static Action<T1, T2, T3> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T4 arg4)
            => (arg1, arg2, arg3) => function(arg1, arg2, arg3, arg4);
        
        // 9
        public static Action<T2, T3> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T4 arg4)
            => (arg2, arg3) => function(arg1, arg2, arg3, arg4);
        
        // 10
        public static Action<T1, T3> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T2 arg2, T4 arg4)
            => (arg1, arg3) => function(arg1, arg2, arg3, arg4);
        
        // 11
        public static Action<T3> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T2 arg2, T4 arg4)
            => (arg3) => function(arg1, arg2, arg3, arg4);
        
        // 12
        public static Action<T1, T2> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T3 arg3, T4 arg4)
            => (arg1, arg2) => function(arg1, arg2, arg3, arg4);
        
        // 13
        public static Action<T2> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T3 arg3, T4 arg4)
            => (arg2) => function(arg1, arg2, arg3, arg4);
        
        // 14
        public static Action<T1> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T2 arg2, T3 arg3, T4 arg4)
            => (arg1) => function(arg1, arg2, arg3, arg4);
    }
}
