using System;

namespace Curryfy
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a tool. 
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public static partial class PartialIncrementalFuncExtensions
    { 
        // 1
        public static Func<T2, T3, T4, T5, T6, T7, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, TResult>(this Func<T1, T2, T3, T4, T5, T6, T7, TResult> function, T1 arg1)
            => (arg2, arg3, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        
        // 2
        public static Func<T3, T4, T5, T6, T7, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, TResult>(this Func<T1, T2, T3, T4, T5, T6, T7, TResult> function, T1 arg1, T2 arg2)
            => (arg3, arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        
        // 3
        public static Func<T4, T5, T6, T7, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, TResult>(this Func<T1, T2, T3, T4, T5, T6, T7, TResult> function, T1 arg1, T2 arg2, T3 arg3)
            => (arg4, arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        
        // 4
        public static Func<T5, T6, T7, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, TResult>(this Func<T1, T2, T3, T4, T5, T6, T7, TResult> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
            => (arg5, arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        
        // 5
        public static Func<T6, T7, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, TResult>(this Func<T1, T2, T3, T4, T5, T6, T7, TResult> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
            => (arg6, arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        
        // 6
        public static Func<T7, TResult> ApplyPartial<T1, T2, T3, T4, T5, T6, T7, TResult>(this Func<T1, T2, T3, T4, T5, T6, T7, TResult> function, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
            => (arg7) => function(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
}
