using System;

namespace Curryfy
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    // This code was generated by a tool. 
    // 
    // Changes to this file may cause incorrect behavior and will be lost if 
    // the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public static partial class PartialIncrementalActionExtensions
    { 
        // 1
        public static Action<T2, T3, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1)
            => (arg2, arg3, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 2
        public static Action<T3, T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T2 arg2)
            => (arg3, arg4) => function(arg1, arg2, arg3, arg4);
        
        // 3
        public static Action<T4> ApplyPartial<T1, T2, T3, T4>(this Action<T1, T2, T3, T4> function, T1 arg1, T2 arg2, T3 arg3)
            => (arg4) => function(arg1, arg2, arg3, arg4);
    }
}
